name: Docker Push

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Checkout repository
        uses: actions/checkout@v2
      -
        name: Get current image version
        id: get_image_version
        run: |
          image_version=$(docker run --rm <your_docker_image> --version)
          echo "::set-output name=image_version::$image_version"
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Get version file
        run: |
          version_file=$(cat version)
          echo "::set-output name=version_file::$version_file"
      -
        name: Compare versions
        id: compare_versions
        run: |
          if [[ "${{ steps.get_image_version.outputs.image_version }}" == "${{ steps.compare_versions.outputs.version_file }}" ]]; then
            echo "::set-output name=build_needed::false"
          else
            echo "::set-output name=build_needed::true"
          fi
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: aaronlee/miniflux-postgres:15-bullseye,aaronlee/miniflux-postgres:15.3-bullseye
        if: steps.compare_versions.outputs.build_needed == 'true'
      -
        name: Update version file
        run: echo "${{ steps.get_image_version.outputs.image_version }}" > version
