name: Docker Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get PostgreSQL version from Docker image
        id: docker_version
        run: |
          docker pull postgres:15
          echo "::set-output name=version::$(docker run --rm postgres:15 postgres --version | awk '{print $3}')"

      - name: Read version from file
        id: version
        run: echo "::set-output name=version::$(cat version)"

      - name: Check if Docker image needs to be built
        id: check_build
        run: |
          if [[ "${{ steps.docker_version.outputs.version }}" != "${{ steps.version.outputs.version }}" ]]; then
            echo "::set-output name=build::true"
          else
            echo "::set-output name=build::false"
          fi

      - name: Write version to file
        if: steps.check_build.outputs.build == 'true'
        run: |
          echo "${{ steps.docker_version.outputs.version }}" > version.txt
          echo "version.txt" > .gitignore

      - name: Create or update version file
        if: steps.check_build.outputs.build == 'true'
        uses: actions/create-file@v2
        with:
          path: version
          content: |
            ${{ steps.docker_version.outputs.version }}

      - name: Build and push Docker image
        if: steps.check_build.outputs.build == 'true'
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          docker build -t aaronlee/miniflux-postgres:15-bullseye-slim .
          docker login -u $DOCKER_USERNAME -p $DOCKERHUB_TOKEN
          docker push aaronlee/miniflux-postgres:15-bullseye-slim
