name: Docker Build and Publish

on:
  push:
    branches:
      - main
    schedule:
      - cron: "33 1 */7 * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get PostgreSQL version from Docker image
        id: docker_version
        run: |
          docker pull postgres:15
          echo "::set-output name=version::$(docker run --rm postgres:15 postgres --version | awk '{print $3}')"

      - name: Read version from file
        id: version
        run: echo "::set-output name=version::$(cat version)"

      - name: Check if Docker image needs to be built
        id: check_build
        run: |
          if [[ "${{ steps.docker_version.outputs.version }}" != "${{ steps.version.outputs.version }}" ]]; then
            echo "::set-output name=build::true"
          else
            echo "::set-output name=build::false"
          fi

      - name: Write version to file
        if: steps.check_build.outputs.build == 'true'
        run: |
          echo "${{ steps.docker_version.outputs.version }}" > version.txt
          echo "version.txt" > .gitignore

      - name: Create or update version file
        if: steps.check_build.outputs.build == 'true'
        run: |
          echo "${{ steps.docker_version.outputs.version }}" > version

      - name: Extract version prefix
        id: extract_version_prefix
        run: |
          echo "::set-output name=version_prefix::${{ steps.docker_version.outputs.version }}" | cut -c 1-2

      - name: Login to Docker Hub
        if: steps.check_build.outputs.build == 'true'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set timestamp
        id: set-timestamp
        run: echo "::set-output name=timestamp::$(date +%Y%m%d%H%M%S)"

      - name: Build and push Docker image
        if: steps.check_build.outputs.build == 'true'
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm64,linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/miniflux-postgres:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/miniflux-postgres:${{ steps.docker_version.outputs.version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/miniflux-postgres:${{ steps.docker_version.outputs.version }}-${{ steps.set-timestamp.outputs.timestamp }}
            ${{ secrets.DOCKERHUB_USERNAME }}/miniflux-postgres:${{ steps.extract_version_prefix.outputs.version_prefix }}
            
      - name: Configure Git credentials
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your-email@example.com"

      - name: Commit and push version file
        if: steps.check_build.outputs.build == 'true'
        run: |
          git add version
          git commit -m "Update version file"
          git push origin HEAD:main
