name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker@v1

      - name: Compare versions
        id: compare-versions
        run: |
          DOCKER_VERSION=$(docker run --rm postgres:15 sh -c "postgres --version" | awk '{print $3}')
          CURRENT_VERSION=$(cat version)
          if [ "$CURRENT_VERSION" = "$DOCKER_VERSION" ]; then
            echo "::set-output name=skip_build::true"
          else
            echo "::set-output name=skip_build::false"
            echo "$DOCKER_VERSION" > version

      - name: Build and publish Docker image
        if: steps.compare-versions.outputs.skip_build == 'false'
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo $DOCKERHUB_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin
          docker build -t ${{ secrets.DOCKER_USERNAME }}/miniflux-postgres:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/miniflux-postgres:latest
