name: Docker Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Compare versions
        id: compare-versions
        run: |
          CURRENT_VERSION=$(cat version)
          DOCKER_VERSION=$(docker run --rm postgres:15 cat /version.txt)
          if [ "$CURRENT_VERSION" = "$DOCKER_VERSION" ]; then
            echo "::set-output name=skip_build::true"
          else
            echo "::set-output name=skip_build::false"
          fi

      - name: Build and publish image
        if: steps.compare-versions.outputs.skip_build == 'false'
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo $DOCKERHUB_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin
          docker build -t your-docker-image:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/miniflux-postgres:latest ${{ secrets.DOCKER_USERNAME }}/miniflux-postgres:${{ github.sha }}
          docker tag ${{ secrets.DOCKER_USERNAME }}/miniflux-postgres:latest ${{ secrets.DOCKER_USERNAME }}/miniflux-postgres:${{ github.sha }}-$(date +%Y%m%d%H%M%S)
          docker push ${{ secrets.DOCKER_USERNAME }}/miniflux-postgres:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/miniflux-postgres:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/miniflux-postgres:${{ github.sha }}-$(date +%Y%m%d%H%M%S)

